### ISSUE TITLE
Support proper Python syntax highlighting for `__str__`/`__repr__`

### ISSUE THREAD

**Issue by AdamHillier** [larq/zookeeper#92]
It would be nicer to use proper Python syntax highlighting. [`prompt-toolkit`](https://python-prompt-toolkit.readthedocs.io/en/stable/pages/printing_text.html#pygments-token-text-tuples) has support for this already. Though this is not something we need to look into right now.

_Originally posted by @lgeiger in https://github.com/larq/zookeeper/pull/91#issuecomment-571094393_

**Comment by lgeiger** [comment]
Probably we want to do something like:
```python
import pygments
from pygments.token import Token
from pygments.lexers.python import PythonLexer

from prompt_toolkit.formatted_text import PygmentsTokens
from prompt_toolkit import print_formatted_text

class Component:
    def summary(self):
        tokens = list(pygments.lex(self.__str__(), lexer=PythonLexer()))
        print_formatted_text(PygmentsTokens(tokens))
```
Plus some additional  to make `pygments` an optional dependency (which is already installed when run locally if people use  `ipython`).

**Comment by lgeiger** [comment]
This would look something like this:
<img width="1552" alt="Screenshot 2020-01-06 at 21 28 29" src="https://user-images.githubusercontent.com/13285808/71846765-a3092000-30cb-11ea-98b6-d08e71c2265c.png">
I am not sure if I prefer that to what we currently have on master:
<img width="1552" alt="Screenshot 2020-01-06 at 11 05 02" src="https://user-images.githubusercontent.com/13285808/71846764-a3092000-30cb-11ea-81f6-be4478e87d25.png">

**Comment by AdamHillier** [comment]
I want to somehow nicely highlight which values have been overriden, and I'm not 100% sure how we would do that under this setup

**Comment by lgeiger** [comment]
> I want to somehow nicely highlight which values have been overriden, and I'm not 100% sure how we would do that under this setup

Yes, I think proper Python syntax highlighting is not the way to go then.
